### PR TITLE
Adds endianess to getBits()

### PR DESCRIPTION
**Pull request by zorce**

### CODE REVIEW

**Comment by inolen** [comment]
Sorry for totally slacking on this. Is this still needed? If so, it'd probably be better to move this conditional to a higher-level such that there's not a conditional per-bit read for something that I imagine would normally be constant for the entire view.

**Comment by AppLover69** [comment]
I specifically would love (and actually need) such a feature.

**Comment by icewind1991** [comment]
@zorce @AppLover69 is it specificly needed to be able to specify the endianess for every single write or would a buffer-wide endianess option cover the use cases?

**Comment by zorce** [comment]
Buffer-wide is sufficient for my needs.

Br, Dennis

**Comment by icewind1991** [comment]
Moving the endianess parameter to the buffer constructor  and finding out a proper way not to have to do the check per bit read would make it good to merge in my eyes

**Comment by icewind1991** [comment]
Superseded by #18

**Pull request closed without merging**
